# Generated by Django 5.1.3 on 2024-12-02 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('config', models.JSONField()),
                ('processor_type', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('MATTERMOST', 'Mattermost'), ('EMAIL', 'Email'), ('VIBER', 'Viber'), ('WHATSUP', 'WhatsUp'), ('SLACK', 'Slack')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('alert_target', models.CharField(max_length=20)),
                ('alert_pause_duration_minutes', models.PositiveIntegerField(default=1)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.alertprocessor')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('alert_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.alertconfig')),
            ],
        ),
    ]
