# Generated by Django 5.1.3 on 2024-12-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alertconfig_enabled'),
        ('cctv', '0016_camera_alert_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='camera_check',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cctv.check'),
            preserve_default=False,
        ),
    ]
