# Generated by Django 5.1.3 on 2024-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alert_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertprocessor',
            name='processor_type',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('MATTERMOST', 'Mattermost'), ('EMAIL', 'Email'), ('VIBER', 'Viber'), ('WHATSAPP', 'WhatsApp'), ('SLACK', 'Slack')], max_length=25),
        ),
    ]
