# Generated by Django 5.1.3 on 2024-11-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
