# Generated by Django 5.1.3 on 2024-11-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_alter_camera_status'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='status',
        ),
        migrations.AddField(
            model_name='camera',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
