# Generated by Django 5.1.3 on 2024-11-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_remove_camera_status_camera_periodic_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='last_checked',
        ),
    ]
