# Generated by Django 5.1.3 on 2024-11-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_remove_camera_last_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('image', models.ImageField(upload_to='checks')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctv.camera')),
            ],
        ),
    ]
