# Generated by Django 5.1.3 on 2024-11-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_checkperiodictask_alter_camera_periodic_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='periodic_task',
        ),
        migrations.AddField(
            model_name='checkperiodictask',
            name='camera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cctv.camera'),
        ),
    ]
