# Generated by Django 5.1.3 on 2024-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0007_remove_camera_periodic_task_checkperiodictask_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='checks'),
        ),
    ]
