# Generated by Django 5.1.3 on 2024-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0009_tag_camera_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip_address_save',
            field=models.CharField(default='', max_length=100),
        ),
    ]
