# Generated by Django 5.1.3 on 2024-11-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0010_camera_ip_address_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='ip_address_save',
            new_name='ip_address_safe',
        ),
    ]
