# Generated by Django 5.1.3 on 2024-11-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0011_rename_ip_address_save_camera_ip_address_safe'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_image_interval', models.PositiveIntegerField(default=1)),
                ('camera', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cctv.camera')),
                ('image_ttl', models.ForeignKey(blank=True, help_text='Image Time To Live. Images older than this interval will be deleted from storage.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule', verbose_name='Image Time To Live')),
            ],
        ),
    ]
