# Generated by Django 5.1.3 on 2024-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('cctv', '0015_alter_duration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='alert_configs',
            field=models.ManyToManyField(to='alert.alertconfig'),
        ),
    ]
