# Generated by Django 5.1.3 on 2024-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('bucket_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=50)),
                ('encrypted_access_key', models.TextField()),
                ('encrypted_secret_key', models.TextField()),
            ],
            options={
                'verbose_name': 'S3 Configuration',
                'verbose_name_plural': 'S3 Configurations',
            },
        ),
    ]
